### ISSUE TITLE
Current download crashes on startup

### ISSUE THREAD

**Issue by lhaig** [tomboy-notes/tomboy.osx#43]
Hi,

I am on 10.10 and when I start the app it seems to start then crashes.
I have tried to build the app from scratch but that does not help below is the error when I run it in debug.
![screen shot 2014-12-02 at 08 21 18](https://cloud.githubusercontent.com/assets/329713/5258696/882f8822-79fc-11e4-98b3-2db0bf571a25.png)

I hope that helps

**Comment by rashoodkhan** [comment]
@lhaig - The issue is fixed in the latest version (master branch). Thanks!

**Comment by lhaig** [comment]
Fantastic Thanks
