### ISSUE TITLE
How does Tomboy OSX relate to Gnome Tomboy?

### ISSUE THREAD

**Issue by retorquere** [tomboy-notes/tomboy.osx#48]
Gnome Tomboy is currently at 1.15.4 (although the latest OSX build I see on their download page is 1.6.0). The download from tomboy.osx has "0.3.4" in the name. How do these versions relate? And will plugins for Gnome tomboy work with tomboy.osx?

**Comment by trepidity** [comment]
The versions do not relate right now. Version 1.6.0 of OSX is no longer supported and probably doesn't work for most.

tomboy.osx 0.3.4 is where all the work is going, but it hasn't been very active this year. Currently, the OSX version doesn't support any plugins :( sorry
